[profile.default]
src = 'contracts'
solc = '0.8.18'
out = 'out'
libs = ['lib', 'vendor']
test = 'contracts/v0.8/tests'
cache_path = 'foundry-cache'
optimizer = true
evm_version = 'paris'

[fuzz]
runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
